### PR TITLE
fix: only upload if resume is present

### PR DESCRIPTION
**Pull request by agarwalviraj**
Call the upload resume function only if a resume has been selected

### CODE REVIEW

**Comment by shawshankkumar** [comment]
@sm-sami @agarwalviraj what are we doing with this?

**Comment by shawshankkumar** [comment]
since it is over, fix and close this @sm-sami @SaanviKumar13 @YARE0909

**Comment by sm-sami** [comment]
not required anymore (at least for now)

**Comment by shawshankkumar** [comment]
I mean its better to get it fixed now instead of fixing it later next year

**Pull request closed without merging**
